name: quiz_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  # core: useful to share code between layers
  core:
    path: core
  # data layer: All the input data stuff (from async sources)
  data:
    path: data
  # domain layer: the business layer, manipulating pure entities through usecases.
  domain:
    path: domain
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  font_awesome_flutter: ^8.10.0
  flutter_custom_clippers: ^1.1.2
  html_unescape: ^1.0.2
  auto_size_text: ^2.1.0
  flutter_localizations:
    sdk: flutter
  google_fonts: ^1.1.1
  # Local cache
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  # Bloc for state management
  bloc: ^6.1.0
  flutter_bloc: ^6.1.1
  # Service locator
  get_it: ^5.0.1
  injectable: ^1.0.5
  # Localization
  flutter_lokalise: ^0.1.2
  # Value equality
  equatable: ^1.2.5
  # Functional programming thingies
  dartz: ^0.9.2
  # Remote API
  data_connection_checker: ^0.3.4
  http: ^0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.8.2
  build_runner: ^1.10.7
  build_web_compilers: ^2.12.0
  mockito: ^4.1.3

flutter:
  uses-material-design: true
  assets:
    - assets/json/
    - assets/images/